env_name: "hospital"
radius: 0.5
num_dyn_circle: 0                   #or 5 to add walking humans into the environment

### Robot Path Settings:
target: [-10., 0.]
init_state: [-14.,0.0]

### Controller Settings (fixed):
threeD_controller: True
nominal_speed: 1.0
MCBF: True                          #or False to use regular CBF
autotune: True

### Controller Settings:
dir_num: 21
ve: 0.5
beta_coef: 1.0
om_expand_threshold: 3.0
target_range: 2.0
om_range: 3.0

hold_time: 1
base_margin: 0.0

### geodesic approximation settings
w: 0.1                              
iter: 100
custom_iter1: NA                    #not used when is not NA
custom_iter2: NA                    #not used when is not NA
iter_g: 10
iter_c: 20