env_name: "hospital"
radius: 0.5                         #the radius for humans approximated as circles
num_dyn_circle: 0                   #or 5 to add walking humans into the environment

### Robot Path Settings:
target: [-10., -5.5]
init_state: [-6.,5.5]

### Controller Settings (fixed):
threeD_controller: True
nominal_speed: 1.0
MCBF: True                          #or False to use regular CBF
autotune: True

### Controller Settings:
dir_num: 21                         #number of e_vec candidates sampled in geodesic
                                    #approximation 

ve: 0.5                             #0.0-1.0 how closely should the robot follow 
                                    #on-Manifold tangent hyperplane vector computed

beta_coef: 1.0                      #coef to compute step size (beta) input into geodesic 
                                    #approximator

om_expand_threshold: 3.0            #when the robot distance is below the threshold, 
                                    #it should select tangent hyperplane vector from 
                                    #the boundary manifold (i.e h=0) instead of the 
                                    #Manifold that the robot is currently on

target_range: 2.0                   #Deactive obstacle switcher inside the tangent  
                                    #hyperplane computation when robot is within this
                                    #distance to the target

om_range: 3.0                       #The detecting range of the robot's ideal onboard  
                                    #sensors

hold_time: 1                        #For how many time steps, should the robot follow
                                    #the newly computed tangent hyperplane vector

base_margin: 0.0

### geodesic approximation settings
w: 0.1                              #parameter w in barrier function h_OH

iter: 100                           #iterations that the geodesic approximator runs
                                    #for concave environmental obstacles

custom_iter1: NA                    #not used when is not NA

custom_iter2: NA                    #not used when is not NA

iter_g: 10                          #iterations the robot takes to convert its states 
                                    #from the current manifold to the on boundary
                                    #manifold (i.e. h = 0)

iter_c: 20                          #iterations that the geodesic approximator runs
                                    #for dynamic humans modeled as cylinders