env_name: "vicon"
radius: 0.5                         
num_dyn_circle: 0                   

### Robot Path Settings:
target: [3., 0.]
init_state: [0.,0.5]

### Controller Settings (fixed):
threeD_controller: True
nominal_speed: 1.0
MCBF: True                          #or False to use regular CBF
autotune: True

### Controller Settings:
dir_num: 51
ve: 0.8
beta_coef: 1.0
om_expand_threshold: 3.0
target_range: 2.0
om_range: 1.0

hold_time: 1
base_margin: 0

### geodesic approximation settings
w: 0.05                              
iter: 100
custom_iter1: NA                    #not used when is not NA
custom_iter2: NA                    #not used when is not NA
iter_g: 10
iter_c: 20