env_name: "hospital"
radius: 0.5
num_dyn_circle: 0                   #or 5 to add walking humans into the environment

### Robot Path Settings:
target: [-14., 0.]
init_state: [-5.,0.0]

### Controller Settings (fixed):
threeD_controller: True
nominal_speed: 1.0
MCBF: True                          #or False to use regular CBF
autotune: False

### Controller Settings:
dir_num: 20
ve: NA                              #not used in handtuned mode
beta_coef: NA                       #not used in handtuned mode
om_expand_threshold: NA             #not used in handtuned mode
target_range: NA                    #not used in handtuned mode
om_range: 3.0                       

hold_time: 1
base_margin: 0.0

### geodesic approximation settings
w: 0.01
iter: 45
custom_iter1: NA                     #not used when is not NA
custom_iter2: NA                     #not used when is not NA
iter_g: 10
iter_c: 20